sync_time:
  name: Sync Clock on Samsung devices via SmartThings
  description: Set the current clock on Samsung ovens through the SmartThings integration.
  fields:
    device_id:
      name: Device
      description: The target device for this action.
      required: true
      example: "abcd1234efghijklmnop"
      selector:
        device:
          filter:
            - integration: smartthings

send_command:
  name: Execute commnad on Samsung devices via SmartThings
  description: Executes the arbitraty command on Samsung device through the SmartThings integration.
  fields:
    device_id:
      name: Device
      description: The target device for this action.
      required: true
      example: "abcd1234efghijklmnop"
      selector:
        device:
          filter:
            - integration: smartthings

    capability:
      name: Capability
      description: The name of the SmartThing capability. It need to be key of [pysmartthing.capability.Capability](https://github.com/pySmartThings/pysmartthings/blob/main/src/pysmartthings/capability.py) enum class.
      required: true
      example: "REFRESH"
      selector:
        text:

    command:
      name: Command
      description: The name of the command. It need to be key of [pysmartthing.command.Command](https://github.com/pySmartThings/pysmartthings/blob/main/src/pysmartthings/command.py) enum class.
      required: true
      example: "REFRESH"
      selector:
        text:

    component:
      name: Component
      description: The name of component.
      required: true
      example: "main"
      default: "main"
      selector:
        text:

    arguments:
      name: Arguments
      description: The arguments that will be passed to command.
      required: false
      example: "abcd1234efghijklmnop"
      selector:
        object:
